import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { ThemeInit } from "../../.flowbite-react/init";
import { NavbarComponent } from "@/src/components/Navbar";
import { AuthProvider } from "../context/AuthContext";
import { ToastProvider } from "../context/ToastContext";
// @ts-ignore
import "./globals.css";
// @ts-ignore
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`flex min-h-screen flex-col bg-white antialiased dark:bg-gray-900`}
      >
        <AuthProvider>
          <ToastProvider>
            <NavbarComponent />
            <ThemeInit />
            {children}
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
